# rna_adata_path: /nfs/homedirs/pala/scportrait_ot/project_folder/data/scrnaseq/sce_converted_processed_discovery.h5ad
rna_adata_path: /lustre/groups/ml01/workspace/alessandro.palma/scportrait/data/scrnaseq/sce_converted_processed_discovery.h5ad
# codex_adata_path: /nfs/homedirs/pala/scportrait_ot/project_folder/data/codex/cellfeaturization_results_healthy_processed.h5ad
codex_adata_path: /lustre/groups/ml01/workspace/alessandro.palma/scportrait/data/codex/cellfeaturization_results_healthy_processed.h5ad
label_columns: ["annotation_figure_1"]
obsm_key_rna: HARMONY
obsm_key_codex: Null
rna_sampling_label: annotation_figure_1 
uniform_sampling_rna: True