rna_adata_path: path_to_citeseq_data/CITEseq_protein_processed.h5ad
codex_adata_path: path_to_codex_data/cellfeaturization_results_tonsilitis_processed_std.h5ad
label_columns: ["annotation_figure_1"]
obsm_key_rna: X_harmony_RNA
obsm_key_codex: Null
rna_sampling_label: annotation_figure_1 
uniform_sampling_rna: False