# === Dataset configuration ===
adata_path: /home/icb/alessandro.palma/environment/scportrait_ot/project_folder/data/citeseq/CITEseq_rna_processed.h5ad
count_label: X_normalized_log
embedding_label: X_harmony_RNA
batch_label: donor_id

# === Model configuration ===
dims: [64, 64]
batch_norm: false
dropout: false
dropout_p: 0.0
batch_encoding: false
batch_encoding_dim: Null
learning_rate: 0.001
likelihood: log

# === Training configuration ===
batch_size: 256
max_epochs: 200
training_dir: /home/icb/alessandro.palma/environment/scportrait_ot/project_folder/experiements  # can be overridden by hydra runtime config
project: decoder_cite_log